### ISSUE TITLE
draw your own polygon

### ISSUE THREAD

**Issue by jmcbroom** [CityOfDetroit/crime-viewer#21]

**Comment by jmcbroom** [comment]
we should think about:
- draw your own poly
- intersect with census blocks
- aggregate those blocks as your new poly
- then we can filter based on block and not spatially

**Comment by jessicamcinchak** [comment]
rather than snapping to census blocks (and introducing census blocks altogether), how about displaying a buffer around the line of the polygon you draw to visually indicate a margin of error due to randomization? Eg points that show up within the buffer may or may not have actually occurred in your custom area, but are nearby
